import { Course, Task, StudySession, DailyActivity, UserProfile } from '@/types';

// DEMO DATA - Computer Science Final Year Student Profile
export const DEMO_USER: UserProfile = {
  name: 'Alex Rivera',
  role: 'CS Senior',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  major: 'Computer Science',
  academicYear: 'Final Year (2026)',
  university: 'Tech University',
  weeklyTargetHours: 25,
};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    code: 'CS401',
    name: 'Distributed Systems & Cloud Architecture',
    color: '#4F46E5', // Indigo
    instructor: 'Dr. Marcus Vance',
    progress: 75,
    totalTasks: 12,
    completedTasks: 9,
    credits: 4,
  },
  {
    id: 'course-2',
    code: 'CS420',
    name: 'Machine Learning & Neural Networks',
    color: '#0284C7', // Sky Blue
    instructor: 'Prof. Elena Rostova',
    progress: 60,
    totalTasks: 10,
    completedTasks: 6,
    credits: 4,
  },
  {
    id: 'course-3',
    code: 'CS490',
    name: 'Senior Capstone Project',
    color: '#7C3AED', // Violet
    instructor: 'Dr. Sarah Jenkins',
    progress: 82,
    totalTasks: 15,
    completedTasks: 12,
    credits: 6,
  },
  {
    id: 'course-4',
    code: 'CS380',
    name: 'Database Security & Cryptography',
    color: '#059669', // Emerald
    instructor: 'Dr. Alan Turing Jr.',
    progress: 45,
    totalTasks: 8,
    completedTasks: 3,
    credits: 3,
  },
  {
    id: 'course-5',
    code: 'CS315',
    name: 'Human-Computer Interaction',
    color: '#D97706', // Amber
    instructor: 'Prof. Maya Lin',
    progress: 90,
    totalTasks: 10,
    completedTasks: 9,
    credits: 3,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Raft Consensus Algorithm Implementation',
    courseId: 'course-1',
    courseCode: 'CS401',
    dueDate: '2026-10-12',
    dueTime: '23:59',
    priority: 'high',
    type: 'assignment',
    completed: false,
    description: 'Implement leader election and log replication using Go or Node.js.',
  },
  {
    id: 'task-2',
    title: 'Capstone Phase 1 UI Architecture Report',
    courseId: 'course-3',
    courseCode: 'CS490',
    dueDate: '2026-10-14',
    dueTime: '17:00',
    priority: 'high',
    type: 'project',
    completed: false,
    description: 'Submit component hierarchy diagram, wireframes, and tech stack rationale.',
  },
  {
    id: 'task-3',
    title: 'Midterm Exam: Machine Learning Concepts',
    courseId: 'course-2',
    courseCode: 'CS420',
    dueDate: '2026-10-16',
    dueTime: '10:00',
    priority: 'high',
    type: 'exam',
    completed: false,
    description: 'Covers backpropagation, CNNs, Transformers, and hyperparameter tuning.',
  },
  {
    id: 'task-4',
    title: 'RSA & AES Cryptography Problem Set',
    courseId: 'course-4',
    courseCode: 'CS380',
    dueDate: '2026-10-18',
    dueTime: '23:59',
    priority: 'medium',
    type: 'assignment',
    completed: false,
    description: 'Solve mathematical problems related to modular exponentiation and public keys.',
  },
  {
    id: 'task-5',
    title: 'HCI Heuristic Evaluation Report',
    courseId: 'course-5',
    courseCode: 'CS315',
    dueDate: '2026-10-20',
    dueTime: '14:00',
    priority: 'low',
    type: 'assignment',
    completed: true,
    description: 'Evaluate mobile app interface against Nielsen 10 Usability Heuristics.',
  },
  {
    id: 'task-6',
    title: 'Distributed Storage Lab 3',
    courseId: 'course-1',
    courseCode: 'CS401',
    dueDate: '2026-10-22',
    dueTime: '23:59',
    priority: 'medium',
    type: 'assignment',
    completed: false,
    description: 'Simulate network partition tolerance and vector clocks.',
  },
];

export const INITIAL_STUDY_SESSIONS: StudySession[] = [
  {
    id: 'session-1',
    courseId: 'course-1',
    courseCode: 'CS401',
    courseName: 'Distributed Systems',
    startTime: '08:30 AM',
    endTime: '10:00 AM',
    durationMinutes: 90,
    activity: 'Review Raft Consensus leader election algorithm & node states',
    date: '2026-10-09',
    completed: true,
    status: 'completed',
  },
  {
    id: 'session-2',
    courseId: 'course-3',
    courseCode: 'CS490',
    courseName: 'Senior Capstone',
    startTime: '10:30 AM',
    endTime: '12:30 PM',
    durationMinutes: 120,
    activity: 'Draft Phase 1 UI design system, color scheme, and component library',
    date: '2026-10-09',
    completed: true,
    status: 'completed',
  },
  {
    id: 'session-3',
    courseId: 'course-2',
    courseCode: 'CS420',
    courseName: 'Machine Learning',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    durationMinutes: 120,
    activity: 'Practice backpropagation derivations & matrix gradient calculations',
    date: '2026-10-09',
    completed: false,
    status: 'in_progress',
  },
  {
    id: 'session-4',
    courseId: 'course-4',
    courseCode: 'CS380',
    courseName: 'Database Security',
    startTime: '05:00 PM',
    endTime: '06:30 PM',
    durationMinutes: 90,
    activity: 'Read Chapter 5: Asymmetric Encryption & Diffie-Hellman Key Exchange',
    date: '2026-10-09',
    completed: false,
    status: 'scheduled',
  },
];

export const INITIAL_WEEKLY_ACTIVITY: DailyActivity[] = [
  { day: 'Monday', shortDay: 'Mon', hours: 3.5, date: '2026-10-05' },
  { day: 'Tuesday', shortDay: 'Tue', hours: 4.0, date: '2026-10-06' },
  { day: 'Wednesday', shortDay: 'Wed', hours: 5.5, date: '2026-10-07' },
  { day: 'Thursday', shortDay: 'Thu', hours: 2.5, date: '2026-10-08' },
  { day: 'Friday', shortDay: 'Fri', hours: 3.5, date: '2026-10-09', isToday: true },
  { day: 'Saturday', shortDay: 'Sat', hours: 1.0, date: '2026-10-10' },
  { day: 'Sunday', shortDay: 'Sun', hours: 0.0, date: '2026-10-11' },
];
